create table sensor
(
    name varchar(30) primary key check ( 3 <= length(name) and length(name) <= 30 )
);

create table measurement
(
    id          int generated by default as identity primary key,
    value       float     not null check (-100 <= value and value <= 100),
    raining     boolean   not null,
    created_at  timestamp not null,
    sensor_name varchar(30) references sensor (name) on delete set null on update cascade
);